export const benlikTasarimiConfig = {
    id: "benlik_tasarimi",
    title: "BENLİK TASARIMI ENVANTERİ",
    desc: "Aşağıdaki cümlelerden her birini dikkatle okuyun. Cümle sizin kişiliğinizi, düşünce ve duygularınızı tamamıyla yansıtıyorsa 'Tam Benim Gibi', biraz uygun düşüyorsa 'Biraz Benim Gibi', karar veremiyorsanız 'Kararsızım', uymuyorsa 'Hayır', kesinlikle uymuyorsa 'Asla' seçeneğini işaretleyiniz.",
    type: "matrix",
    columns: ["Tam Benim Gibi", "Biraz Benim Gibi", "Kararsızım", "Hayır", "Asla"],
    questions: [
        "Sıkılganım ve utangacım.",
        "Kırgınlıklarımın çöküntüsü içindeyim.",
        "İçine kapanık insanım.",
        "Kötü yola sapmaktan korkuyorum.",
        "Sinirliyim.",
        "Günlük işlerimi zevkle yapıyorum.",
        "Şanslı bir insanım.",
        "Okumak ve çalışmak benim için zevkli bir uğraşı.",
        "Yurdumu seviyor ve ilerlemesine katkıda bulunmaya çalışıyorum.",
        "Ölümden çok korkuyorum.",
        "Çabuk tesir altında kalıyorum.",
        "Cinsiyetimden (Kız/Erkek) olmaktan şikâyetçiyim.",
        "Sevilmediğim kanısındayım.",
        "Yakınlarımın baskısına dayanamıyorum.",
        "Ülke sorunlarının er geç çözüleceği kanısındayım.",
        "İnsanlara yardımdan zevk alıyorum.",
        "Problemleri çözmek ve işleri yoluna koymaktan hoşlanıyorum.",
        "Geleceğe umutla bakıyorum.",
        "Yeni denemelere girmekten hoşlanıyorum.",
        "Kimsenin bana önem vermemesine üzülüyorum.",
        "Flört anlamında bir ilişki kurmaktan kaçınıyorum.",
        "İnsanlarla yakın ilişki kurmam, samimi olmak bana zor geliyor.",
        "Yaşamakla ölmek benim için aynıdır.",
        "Kendimi yalnız ve yabancı hissediyorum.",
        "Üzerime sorumluluklar almaktan zevk alıyorum.",
        "Çalışmalarımın topluma yararlı olacağı kanısındayım.",
        "Yaşamaktan zevk alıyorum, moralim yüksek.",
        "Güçlüklerimi yenebilmekteyim.",
        "İnsanların çoğuna güvenim var.",
        "Aşırı derecede alttan alıyorum.",
        "Güç karşısında çabuk pes ediyorum.",
        "Hakkımı korumakta güçlük çekiyorum.",
        "Her şeyi anlamsız buluyorum.",
        "Çoğu zaman kendimi hüzünlü hissediyorum.",
        "Kendimi boş ve gayesiz hissediyorum.",
        "Hiçbir şeyle devamlı ilgilenemiyorum.",
        "Kendimi değersiz ve işe yaramaz hissediyorum.",
        "Rahat konuşuyorum.",
        "Canlı ve neşeliyim.",
        "İçimi rahatça dökebilen açık ve samimi bir insanım.",
        "Sağlıklı ve güçlüyüm.",
        "İyi bir insanım.",
        "Hayatta bütün değer sistemlerine kuşku ile bakıyorum.",
        "Büyüklere isyan duygusu içindeyim.",
        "Diploma almak zorunda olmazsam tahsili hemen bırakırım.",
        "Mutsuzum.",
        "İçimde sürekli bir gerilimin sıkıntısını duymaktayım.",
        "Başkalarıyla işbirliği yapmaktan hoşlanıyorum.",
        "Geçirdiğim hayattan memnunum.",
        "Yapacağım işlerin kıvancını duyuyorum.",
        "Geçirdiğim tecrübeler bana çok şey kazandırdı.",
        "Bütün günlük çatışmalara rağmen evrende bir ahenk ve anlam olduğuna inanıyorum.",
        "Gerektiği zaman hakkını arayabilirim.",
        "Sevgimi ve saygımı açıkça anlatırım.",
        "Başkalarının uygun bulmadığım isteklerine “hayır” diyebilirim.",
        "Kalabalık içinde olmak huzurumu kaçırır.",
        "Sık sık kendimi endişe ve kaygı içinde buluyorum.",
        "Bazı insanlara rastlamamak için yolumu değiştiririm.",
        "Kendimden utanıyorum.",
        "Başkaları seyrederken iş yapmak bana zor geliyor.",
        "Okulda başarısız olsam bile ailem tarafından destekleneceğimden eminim.",
        "Arkadaşlarımla iyi vakit geçiriyorum.",
        "Duygu ve düşüncelerimi kolaylıkla ifade edebiliyorum.",
        "Evim, yaşanılması hoş bir yerdir.",
        "Bana yapılan şakaları hoş karşılıyorum."
    ]
};
