export const calismaDavranisiConfig = {
    id: "calisma_davranisi",
    title: "ÇALIŞMA DAVRANIŞINI DEĞERLENDİRME ÖLÇEĞİ",
    desc: "Aşağıdaki cümlelerde ifade edilenler sizin için her zaman veya genellikle geçerliyse 'Doğru' seçeneğini, her zaman veya genellikle geçerli değilse 'Yanlış' seçeneğini işaretleyiniz. Çalışma davranışınızla ilgili gerçekçi bir değerlendirme ancak sizin gerçekçi olmanızla mümkündür.",
    type: "matrix",
    columns: ["Doğru", "Yanlış"],
    questions: [
        "Derslerle ilgili tekrarlarımın çoğunu sınavdan önceki gece yaparım.",
        "Bir sınava hazırlanırken, sinirlilikten, gerginlikten huzursuzluktan ötürü çalışmakta güçlük çekerim.",
        "Ödevler ve kompozisyonlar bana angarya gelir, bir an önce kurtulmak isterim.",
        "Anlayabilmek için çoğunlukla bir konuyu defalarca okuyorum.",
        "Derse çalışırken önemli noktaları bulup çıkartmakta güçlük çekerim.",
        "Bir dönem ödevini hazırlamaya başlamadan önce mutlaka müsveddesini yaparım.",
        "Bilmediğim veya anlamından emin olmadığım kelimeleri sözlükten bakarım.",
        "Not tutarken, öğretmenin veya yazarın kelimelerini değil kendi kelimelerimi kullanırım.",
        "Bir test sırasında sinirli olurum ve hak ettiğim kadar başarılı olamam.",
        "Derste notlarımı not defteri yerine elime geçen kağıtlara alırım.",
        "Zaman zaman okuduklarımı grafikler, şemalar ve özetler halinde ifade ederim.",
        "Bir cümleyi meydana getiren öğeleri gerçekten bilmiyorum.",
        "Çalışmaya başlamak için çoğunlukla içimden gelmesini beklerim.",
        "Düzenli olarak tekrarlar yaparım.",
        "Çalışmam sırasında telefonla arayanlar, gelen giden ve başka sebepler çalışmaya ara vermemi gerektirir.",
        "Bir başka derse geçmeden önce, başladığım dersi bütünüyle tamamlarım.",
        "Çalışmam için harcamam gereken zamanı oyunda, televizyonun başında, telefonda, müzik dinleyerek, arkadaşlarla geçirdiğim olur.",
        "Zaman zaman, dersin amacının tam olarak ne olduğunu bilmeden, çalışmaya başladığımı fark ederim.",
        "Okulda öğrendiğim derslerle ilgili konulan dış dünyadaki olayları anlayabilmek için kullanırım.",
        "Ders notlarının hepsini not defterimin içinde toplu olarak saklarım.",
        "Kompozisyon ve dönem ödevlerinde sonuç bölümünü yazmakta zorlanıyorum.",
        "Öğretmenin her söylediğini not aldığım ve bunları elden geçirmediğim için bazen gereksiz malzemeyi çalışmak zorunda kalırım.",
        "Bir kompozisyon veya ödev hazırlarken, başlamadan önce bir plan yaparım.",
        "Okuduğum her cümle veya paragraftan sonra not almak yerine, bölümü bitirdikten sonra not çıkartırım.",
        "Kompozisyon veya ödevlerimi vermem gereken günden önce hazır ederim ve böylece birkaç kere okur ve gerekiyorsa yeniden yazarım.",
        "Ödevlerimi bazen zamanında hazır edemem ve yetiştirmek zorunda kalırsam aceleyle hazırlarım.",
        "Bazı öğretmen ve derslerden hoşlanmamam okul başarın etkiler.",
        "Sık sık ne okuduğumu bilmeden sayfalarca okumuş olduğumu fark ederim.",
        "Çoğunlukla okuduğum kitaptaki şekil ve tabloları atlarım.",
        "Bazı dersler için o kadar çok zaman harcıyorum ki, diğer derslere zamanım kalmıyor.",
        "Yeni (bilmediğim) kelimeleri ve anlamlarını yazmak için fihristli bir not defteri tutarım.",
        "Çalışırken çoğunlukla kalkıp dolaşırım, gazete okurum veya bir şeyler atıştırırım.",
        "Çalışmalarımla ilgili bir problemle karşılaşırsam, bunları öğretmenimle konuşmakta tereddüt etmem.",
        "Bazen okurken önemli kelimeleri mırıldanarak veya fısıldayarak tekrar ederim.",
        "Bazı öğretmenlerin beni antipatik bulduğunu hissediyorum.",
        "Doğru cevabı bilsem bile, çoğunlukla sınıfta sorulara cevap vermekten veya tekrarlara katılmaktan çekinirim.",
        "Çoğunlukla uykumu tam olarak alamıyorum ve sınıfta uyukladığımı hissediyorum.",
        "Yeni öğrendiğim kelimeleri uygun durumlarda kullanırım.",
        "Zamana göre düzenlenmiş çalışma programım vardır.",
        "Çalışırken kolayca hayallere dalabilirim.",
        "Bir yazılıda, yazmaya başlamadan önce bütün soru ve talimatları iyice okurum.",
        "Yeni bir bölüme başlamadan önce o konuda fikir sahibi olmaya çalışmak bence zaman kaybıdır.",
        "Çalışma programıma sıkı sıkıya bağlı kalma düşüncesi bana sıkıntı verir, programda sık sık değişiklik yapmakta tereddüt etmem.",
        "Bazen televizyon seyrederken veya odada başkaları konuşurken çalıştığım olur.",
        "Kitaplarımda önemli veya zor bölümleri işaretlerim, böylece tekrarlarken bu noktalara özel dikkat harcamam mümkün olur.",
        "Okurken dinlenme aralarımı bölüm sonlarında veririm ve kendi kendime o bölümün ana noktalarını tekrarlarım.",
        "Öğrendiğim genel prensipleri ve kuralları ortaya koyan belirli örnekler düşünürüm.",
        "Çalışmaya başlamakta güçlük çekerim.",
        "Bazen okula gittiğimde veya çalışmaya oturduğumda kitapları, kalemleri, notları veya gerekli diğer malzemeyi getirmediğimi fark ederim.",
        "Bir derste öğrendiklerimi, bir başka dersteki konuyu anlamak için kullanırım.",
        "Bazen bir konuyu öğrendikten sonra gerekenden fazla tekrar yaparak, unutamayacağım şekilde hafızama yerleştiririm.",
        "Bir ödevi nasıl yazmaya başlayacağımı gerçekten bilmiyorum.",
        "Ödevlerim daima içime bir sıkıntı verir.",
        "Bir sınava hazırlanırken, tam olarak kitaptaki kelimeleri hatırlamaya çalıştığım çok olur.",
        "Dersi doğrudan bir ışık altında değil, yansıyarak gelen bir ışık altında çalışırım.",
        "Bir konuyu ayrıntılı olarak çalışmaya başlamadan önce, genel bir fikir sahibi olabilmek için hızlı bir göz gezdiririm (örneğin paragraf başlıklarını ve altındaki cümleleri okuyarak).",
        "Öğretmenlerimin bana iyi duygular beslediğini hissediyorum.",
        "Sınav başladığı zaman puan değerleri ve güçlük derecelerine bakmaksızın vakit kaybetmeden hemen yazmaya koyulurum.",
        "Birçok sınava, öğrendiklerimi sınav bitinceye kadar aklımda tutmak için çalışırım.",
        "Çabuk, ancak bütünüyle anlayacak kadar hızlı okurum.",
        "Not tutarken kendime ait özel işaretler ve kısaltmalar kullanırım.",
        "Notlarımı derste tuttuğum gibi muhafaza eder bir karışıklığa meydan vermemek için onlara el sürmem.",
        "Bir ödeve başlamadan önce en az bir veya iki kaynağa bakar, güvendiğim kişilerin görüşünü alırım.",
        "Büyük çoğunlukla okul hayatını ilginç buluyorum.",
        "Dersi dinlerken muhtemel sınav sorularına karşı dikkatli olurum ve bunları not alırım.",
        "Sınava girmeden önce öğretmenin nelere önem verdiğiyle ilgilenmem ve sınav biçimiyle ilgili bilgi toplamak için vakit kaybetmem. Çünkü bunlar her yıl değişebilir ve yanıltıcı olabilir.",
        "Çalışma sürelerim oldukça kısadır ve bu sebeple zaman zaman dikkatimi toplamakta zorluk çekerim.",
        "Okula gitmek gerekmeseydi, pek çok şeyi daha kolay öğrenirdim.",
        "Okulda gençliğin en güzel günleri, hayatta kullanılıp kullanılmayacağı çok şüpheli birçok bilgiyi öğrenmek uğruna ziyan ediliyor.",
        "Ders çalışırken verdiğim dinlenme aralarından sonra tekrar derse dönmekte zorluk çekerim.",
        "Derse gelmeden önce işlenecek dersle ilgili okumayı zaman kaybı olarak görürüm.",
        "Öğretmenin anlattıkları kitapta varsa, onları anlamak için bol zamanım olacağı için fazla endişelenmem.",
        "Her kelimenin anlamına dikkat ederek çok yavaş okurum."
    ]
};
