export const cokluZekaConfig = {
    id: "coklu_zeka",
    title: "ÇOKLU ZEKÂ GÖZLEM FORMU",
    desc: "Lütfen formda yer alan her ifadenin sizin için ne derece uygun olup olmadığını aşağıdaki beşli dereceleme ölçeği üzerinde belirtiniz. \n\n0 = BENİM İÇİN HİÇ UYGUN DEĞİL,  1 = ÇOK AZ UYGUN,  2 = KISMEN UYGUN,  3 = OLDUKÇA UYGUN,  4 = TAMAMEN UYGUN",
    type: "matrix",
    columns: ["0", "1", "2", "3", "4"],
    questions: [
        "Dinleyerek daha iyi öğrenirim.",
        "Konuşmadan ve yazmadan önce kelimeleri kafamda tasarlayabilirim",
        "Radyo dinlemeyi televizyon seyretmeye tercih ederim.",
        "Sözcük oyunlarından, şifreli kelime oyunlarından çok hoşlanırım.",
        "Bazen arkadaşlarım kullandığım kelimenin anlamını açıklamamı istiyorlar.",
        "Sosyal konular bana matematik ve fen konularından kolay gelir.",
        "Yürüyüş yaparken cadde boyunca varolan yazılar, resimlerde daha fazla dikkatimi çeker.",
        "Duyduğum ve yeni okuduğum kelimeleri konuşmalarımda kullanmaktan hoşlanırım.",
        "Kitap okumak benim için çok önemlidir.",
        "Çeşitli konularda deneme, şiir, hikaye yazma ve benzeri etkinliklerden birini yaparım.",
        "Zeka oyunları ve soruları ilgimi çeker.",
        "Okuldayken matematik ve fen bilgisi en sevdiğim derslerdi.",
        "Mantıksal düşünme gerektiren oyunlar ve beyin jimnastikleri çok hoşuma gider.",
        "Gelecekle ilgili tahminler yapmak bana eğlenceli gelir.",
        "Her şeyin mantıklı bir açıklaması olduğuna inanırım.",
        "Soyut kavramlarla ilgili düşünmekten hoşlanırım.",
        "İnsanların söylediği, yaptığı işlerin mantığını anlamaya çalışmak hoşuma gider.",
        "Makine ve aletlerin çalışma sistemini merak ederim.",
        "Zihinden hesap yapmak bana kolay gelir.",
        "Sayılarla konuşmayı ve bir konuyu matematiksel olarak ifade etmeyi daha doğru bulurum.",
        "Bir işin ya da olayın bütününü görmek bence önemlidir.",
        "Görsel konuları daha iyi öğrenirim.",
        "Etrafımda gördüklerimi çok ayrıntılı hatırlayabiliyorum.",
        "Görsel bulmacalar çözmekten hoşlanıyorum.",
        "Renkli, hareketli rüyalar görüyorum.",
        "Bilmediğim bir yerde genelde yolumu bulabilirim.",
        "Bir şeyler çizmekten, karalamaktan hoşlanıyorum.",
        "Nesneler ters çevrildiğinde de görünümünü rahatlıkla hayal edebiliyorum.",
        "Resimlerle zenginleştirilmiş kitapları okumayı seviyorum.",
        "Gözlerimi kapadığımda görsel imajlar görebilirim.",
        "Şarkı söylemeyi severim.",
        "Çalışırken radyodan, kasetten müzik dinlemek benim için önemlidir.",
        "Bir müzik aleti çalarım.",
        "Hayatımda müzik olmasaydı eminim hayatım daha fakir olurdu.",
        "Yürürken bir ezgiyi mırıldanırım.",
        "Bir çok parçanın melodisini bilirim.",
        "Bilmediğim bir parçayı bir iki kez dinledikten sonra doğru bir şekilde söylerim.",
        "Çalışırken veya yeni bir şey öğrenirken tempo tutarım.",
        "Çevremdeki seslere çok duyarlıyım.",
        "Müzik derslerini seviyorum.",
        "İnsanlar beni fiziksel olarak çok hareketli bulur.",
        "Araç gereçleri elime alıp parçalarına ayırmayı ve birleştirmeyi severim.",
        "El becerileri gerektiren işleri seviyorum.",
        "En parlak fikirler yürürken ya da fiziki bir etkinlik ile uğraşırken aklıma gelir.",
        "Serbest zamanlarımı dışarıda geçirmeyi seviyorum.",
        "Biriyle konuşurken vücudumu ve ellerimi sık kullanırım.",
        "Bir şey hakkında daha fazla bilgi edinmek için ona dokunmaya ihtiyaç duyarım.",
        "Macera yaşamaktan ya da benzeri ürkütücü fiziksel etkinliklerden hoşlanırım.",
        "En az bir spor dalıyla ya da fiziksel etkinlikle ilgilenirim.",
        "Uzun süre oturmak bana zor gelir.",
        "Hayvanlara karşı çok meraklıyım.",
        "Açık havada oturmak çok hoşuma gider.",
        "Toprakla, bitkilerle uğraşmayı severim.",
        "Doğadaki varlıkları tanımak bana heyecan verir.",
        "Doğayla ilgili mağaza, müze ya da sergileri gezmekten hoşlanırım.",
        "Bir hayvan beslemek ya da çiçek yetiştirmek bence çok gereklidir.",
        "Çevre kirliliğine karşı çok duyarlıyım.",
        "Doğa ile ilgili dergi, kitap ya da belgeselleri takip ederim.",
        "Vakıfların doğayı koruma çalışmalarını çok önemli buluyorum.",
        "Çevre bilinci güçlü insanları değerli buluyorum.",
        "Birilerine bir şeyler öğretmek ve paylaşımda bulunmak hoşuma gider.",
        "Bir yere giderken yada bir iş yaparken yanımda birileri olsun isterim.",
        "Problemim olduğunda arkadaşlarımdan yardım alarak halletmeyi tercih ederim.",
        "Birkaç tane çok yakın arkadaşım vardır.",
        "Kendimi bir lider gibi düşünmüşümdür.",
        "Kalabalıkta kendimi rahat hissederim.",
        "Sosyal etkinliklere katılmaktan hoşlanırım.",
        "Evde yalnız oturmak yerine eğlenceli bir toplantıya katılmayı yeğlerim.",
        "İnsanlar bana zaman zaman fikir danışır.",
        "Grup oyunlarını bireysel oyunlara tercih ederim.",
        "Kendimle baş başa yalnız kalmayı severim.",
        "Kendime güvenim yüksektir.",
        "Kendi başıma uğraştığım özel bir hobim vardır.",
        "Hayatım için bazı önemli hedeflerim var.",
        "Yeteneklerim ve zayıf taraflarım hakkında gerçekçi görüşlere sahibim.",
        "Tek başıma hafta sonunu geçirmeyi kalabalık bir grupla geçirmeye yeğlerim.",
        "Kendimi bağımsız biri olarak düşünmüşümdür.",
        "Duygu ve düşüncelerimi iyi ifade ederim.",
        "Hayatın anlamı hakkında düşünmeyi yada yazmayı severim.",
        "Kendimi daha iyi tanımak için kişisel gelişim kitapları okurum."
    ]
};
