import { abkoConfig } from './abko';
import { burdonConfig } from './burdon';
import { ogrenmeStilleriConfig } from './ogrenmeStilleri';
import { cokluZekaConfig } from './cokluZeka';
import { benlikTasarimiConfig } from './benlikTasarimi';
import { calismaDavranisiConfig } from './calismaDavranisi';
import { hollandConfig } from './holland';

export const INITIAL_GUIDANCE_FORMS_CONFIG = [
    hollandConfig,
    calismaDavranisiConfig,
    benlikTasarimiConfig,
    cokluZekaConfig,
    ogrenmeStilleriConfig,
    burdonConfig,
    abkoConfig,
    { id: 'devamsizlik_detayli', title: 'DEVAMSIZLIK NEDENLERİ ANKETİ', desc: 'Bu ankette devamsızlık nedenlerinizi değerlendirme amaçlı 51 madde yer almaktadır. Her maddenin karşısında "Evet", "Bazen", "Hayır" seçenekleri bulunmaktadır. Sizden beklenen her maddeyi dikkatlice okuyarak boş madde bırakmadan size uygun seçeneğin altındaki parantezin içine işaret koymanızdır. Lütfen maddeleri bu eğitim-öğretim yılını düşünerek işaretleyiniz.', type: 'mixed', questions: [
        { text: "1. İhtiyaç duyduğumda okul idaresi izin vermediği için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "2. Zor dersler aynı günde olduğunda", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "3. Geç kaldığımda okul yöneticileriyle karşılaşmak istemediğim için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "4. Boş derslerde ve öğle aralarında okulda verimli zaman geçireceğim bir alan/mekan olmadığı için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "5. Giriş ve çıkış saatleri bana uygun olmadığı için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "6. Kılık kıyafetim uygun olmadığında (saç, sakal, takı, makyaj vb.) okul yönetiminden çekindiğim için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "7. Okul binası (rampa, asansör vb) fiziksel durumuma uygun olmadığı için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "8. Okulda günlük ders saati çok fazla olduğu için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "9. Okulun ilk ya da son haftalarında ders yapılmadığı için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "10. Okulda yeteneklerimi gösterebileceğim fırsatlar olmadığı için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "11. Öğretmenler aşırı disiplinli davrandığı için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "12. Bazı dersler çok sıkıcı geçtiği için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "13. Öğretmenler, benden derslerde yapabileceklerimden daha fazlasını yapmamı bekledikleri için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "14. Öğretmenler, okulda öğrencilere karşı sürekli küçük düşürücü davranışlarında bulundukları için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "15. Öğretmenler, öğrenciler arasında ayrımcılık yaptığı için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "16. Öğretmenlerim bana yakınlık göstermediği için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "17. Diğer öğrenciler dersin işlenmesine engel olduğu için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "18. Ailem, okula gidip gitmememi umursamadığı için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "19. Ders araç gerecim olmadığında", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "20. Bazı günler harçlığım olmadığı için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "21. Bazı günler kıyafetlerim bakımsız (kirli, ütüsüz) olduğunda", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "22. Aileme yardımcı olmam gereken günlerde", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "23. Okul dışında bir işte çalışmak zorunda olduğum için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "24. Aile içinde sorunlarımız olduğu zamanlarda", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "25. Evde misafir olduğu zaman", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "26. Bir yakınım vefat ettiğinde", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "27. Evim okula çok uzak olduğu için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "28. Havanın soğuk ya da yağışlı olduğu günlerde", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "29. Özel kurs ve etütlere daha fazla zaman ayırdığım için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "30. Okul dışındaki etkinliklere katılmak için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "31. Okul yolu güvenli olmadığı için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "32. Ertesi günün sınavlarına çalışmak için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "33. Ödevlerimi yapmadığım günlerde", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "34. Başarısız olduğum derslere katılmak istemediğim için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "35. Bir üst öğretim kurumunun sınavlarına hazırlanmamda okul dersleri yetersiz kaldığı için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "36. Okulu bitirince iş bulabileceğime inanmadığım için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "37. Okulumu sevmediğim için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "38. Hasta olduğum zaman", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "39. Sabahları zamanında uyanamadığımda", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "40. Yorucu geçen bir günden sonraki günü dinlenerek geçirmek istediğim için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "41. Dersin telafisi mümkün olduğunda", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "42. Resmi tatillerden önceki ya da sonraki günlerde", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "43. Bazı günler moralim bozuk olduğu için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "44. Okuldan kaçmak eğlenceli geldiği için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "45. Okula gitmesem de sınıfı geçeceğimi bildiğim için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "46. Arkadaşlarıma göre yaşça daha büyük olduğum için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "47. Okul saatinde, okul dışından arkadaşlarımla görüşmek için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "48. Arkadaşlarımla okuldan kaçma kararı aldığımızda", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "49. Okulda arkadaşlarım tarafından dışlandığım için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "50. Okuldaki öğrenciler fiziksel veya duygusal olarak bana zarar verdiği için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "51. Okulda arkadaşlarımla anlaşamadığım için", type: 'likert', options: ["Evet", "Bazen", "Hayır"] },
        { text: "52. Belirtmek istediğiniz diğer nedenler varsa yazınız.", type: 'text' }
    ] },

    { id: 'yol_haritam', title: 'Yol Haritam (Zaman Yönetimi Form-I)', desc: 'Bu formu hazırlamaktaki amacımız, zamanını nasıl değerlendirdiğini görerek sana özel bir zaman yönetimi rehberliği sunabilmektir. Senden gün içinde etkinliklere ayırdığın süreleri (15 dk, 1 saat vb.) tabloda ilgili bölüme yazmanı bekliyoruz.', type: 'timetable', columns: [
        "Ders", "TV", "Telefon&Tablet", "Kitap", "Spor/Sanat (Hobi)", "Diğer (Belirtiniz)"
    ], rows: [
        "Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma", "Cumartesi", "Pazar", "Toplam Süre"
    ] },

    { id: 'yol_haritam_2', title: 'Yol Haritam (Zaman Yönetimi Form-II)', desc: 'FORM-2\'yi FORM-1\'den aldığın geri bildirimlere göre yeniden doldurman ve planlarını, planlardan geriye kalanları ve planların dışında yaptıklarını eksiksiz doldurman beklenmektedir. Zaman yönetimi becerin beklediğin düzeye gelene kadar rehberlik servisine danışabilirsin.', type: 'timetable', columns: [
        "Planladıklarım (Ders)", "Planladıklarım (Ders dışı)", "Yaptıklarım", "Kalanlar", "Planım Dışında Yaptıklarım"
    ], rows: [
        "Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma", "Cumartesi", "Pazar", "Haftalık değerlendirme"
    ] },

    { id: 'saa', title: 'ŞAA (Şiddet Algısı Anketi) - Öğrenci', desc: 'Aşağıdaki durumlar sizce şiddet midir? Uygun olanı işaretleyiniz.', type: 'matrix', questions: [
        "Evde çocuğun davranışları nedeniyle harçlığının kesilmesi", "Evde, çocuğun sevdiği şeyleri yapmasının engellenmesi", "Anne babanın çocuğunu başkalarıyla kıyaslaması", "Evde çocuğun özel eşyalarının izinsiz karıştırılması", "Evde çocuğun görmezden gelinmesi", "Evde çocuğa başkalarının yanında mahcup olup utanacağı şeylerin söylenmesi", "Evde çocuğa hakaret edilmesi", "Evde çocuğa yüksek sesle bağırması", "Evde çocuğa kötü isimler takılması", "Evde çocuğun dövülmesi", "Evde çocuğun itilip/kakılması", "Evde çocuğa bir şeyler fırlatılması", "Okulda, bir öğrencinin diğer çocuklar tarafından oyuna alınmaması", "Okulda diğer çocukların başka bir çocuk hakkında dedikodu yapması", "Okuldaki diğer çocukların bir çocuk hakkında aslı olmayan hikayeler uydurması", "Okuldaki diğer çocukların bir çocuğa kötü isimler takması", "Okuldaki diğer çocukların bir çocuğu tehdit etmesi", "Okuldaki diğer çocukların bir çocuğa küfür etmesi", "Okuldaki diğer çocukların bir çocuğun eşyalarını kırıp parçalaması", "Okulda bir çocuğun itilip/çekiştirilmesi", "Okulda arkadaşlarının/akranlarının bir çocuğu dövmesi", "Okulda öğretmenin bir çocuğun kulağını çekmesi", "Okulda öğretmenin bir çocuğa isim takması", "Okulda öğretmenin bir çocuğa hakaret etmesi", "Okulda öğretmenin bir çocuğa bağırması", "Okulda, öğretmenin bir çocuğu dövmesi", "Kantinde bir çocuğun arkadaşları/akranları tarafından itilip/çekiştirilmesi", "Servise binerken arkadaşları/akranları tarafından bir çocuğun sırasının alınması", "Okul çevresinde bir çocuğun tehdit edilmesi", "Okul çevresinde bir çocuğa küfür edilmesi", "Okul çevresinde bir çocuğa hakaret edilmesi", "Okul çevresinde bir çocuğa vurulması", "Okul çevresinde bir çocuğun itilip çekiştirilmesi", "Okul çevresinde bir çocuğun dövülmesi", "Bir çocuğun fotoğraf ya da kaydının cep telefonuyla izin alınmadan kullanılması", "Bir çocuğa Facebook gibi sosyal medya araçlarında hakaret edilmesi", "Sosyal medyada bir çocuğun resimlerine montaj yapılması", "Sosyal medyada bir çocuğun adına sahte hesap açılması", "Bir çocuğun internet ya da cep telefonu üzerinden tehdit edilmesi", "İnternette bir çocuk hakkında söylentiler çıkarılması"
    ], columns: ["Şiddettir", "Kararsızım", "Şiddet Değildir"] },

    { id: 'ssa', title: 'ŞSA (Şiddet Sıklığı Anketi) - Öğrenci', desc: 'Bu bölümde bazı durumlar verilmiştir. Olayların karşısında yer alan "Hiç Olmadı", "Ayda Birkaç Kez Oldu", "Hemen Hemen Her Gün Oldu" ifadelerinden size uygun seçeneğin altındaki parantezin içine (X) işareti koyunuz. İşaretlerken son 6 ayınızı göz önünde bulundurunuz.', type: 'matrix', questions: [
        "Evde çocuğun davranışları nedeniyle harçlığının kesilmesi", "Evde, çocuğun sevdiği şeyleri yapmasının engellenmesi", "Anne babanın çocuğunu başkalarıyla kıyaslaması", "Evde çocuğun özel eşyalarının izinsiz karıştırılması", "Evde çocuğun görmezden gelinmesi", "Evde çocuğa başkalarının yanında mahcup olup utanacağı şeylerin söylenmesi", "Evde çocuğa hakaret edilmesi", "Evde çocuğa yüksek sesle bağırması", "Evde çocuğa kötü isimler takılması", "Evde çocuğun dövülmesi", "Evde çocuğun itilip/kakılması", "Evde çocuğa bir şeyler fırlatılması", "Okulda, bir öğrencinin diğer çocuklar tarafından oyuna alınmaması", "Okulda diğer çocukların başka bir çocuk hakkında dedikodu yapması", "Okuldaki diğer çocukların bir çocuk hakkında aslı olmayan hikayeler uydurması", "Okuldaki diğer çocukların bir çocuğa kötü isimler takması", "Okuldaki diğer çocukların bir çocuğu tehdit etmesi", "Okuldaki diğer çocukların bir çocuğa küfür etmesi", "Okuldaki diğer çocukların bir çocuğun eşyalarını kırıp parçalaması", "Okulda bir çocuğun itilip/çekiştirilmesi", "Okulda arkadaşlarının/akranlarının bir çocuğu dövmesi", "Okulda öğretmenin bir çocuğun kulağını çekmesi", "Okulda öğretmenin bir çocuğa isim takması", "Okulda öğretmenin bir çocuğa hakaret etmesi", "Okulda öğretmenin bir çocuğa bağırması", "Okulda, öğretmenin bir çocuğu dövmesi", "Kantinde bir çocuğun arkadaşları/akranları tarafından itilip/çekiştirilmesi", "Servise binerken arkadaşları/akranları tarafından bir çocuğun sırasının alınması", "Okul çevresinde bir çocuğun tehdit edilmesi", "Okul çevresinde bir çocuğa küfür edilmesi", "Okul çevresinde bir çocuğa hakaret edilmesi", "Okul çevresinde bir çocuğa vurulması", "Okul çevresinde bir çocuğun itilip çekiştirilmesi", "Okul çevresinde bir çocuğun dövülmesi", "Bir çocuğun fotoğraf ya da kaydının cep telefonuyla izin alınmadan kullanılması", "Bir çocuğa Facebook gibi sosyal medya araçlarında hakaret edilmesi", "Sosyal medyada bir çocuğun resimlerine montaj yapılması", "Sosyal medyada bir çocuğun adına sahte hesap açılması", "Bir çocuğun internet ya da cep telefonu üzerinden tehdit edilmesi", "İnternette bir çocuk hakkında söylentiler çıkarılması"
    ], columns: ["Hiç Olmadı", "Ayda Birkaç Kez Oldu", "Hemen Hemen Her Gün Oldu"] },
    
    { id: 'sma', title: 'ŞMA (Şiddet Meşruiyeti Anketi) - Öğrenci', desc: 'Size günlük hayatınızda karşılaşabileceğiniz bazı olaylar ile ilgili hikayeler okuyacağım. Birinci hikayeyi okuduğumda birinci anketi, ikinci hikayeyi okuduğumda ikinci anketi, üçüncü hikayeyi okuduğumda üçüncü anketi doldurmanızı istiyorum.', type: 'story_matrix', 
      columns: ["Haklı Bulmuyorum", "Kararsızım", "Haklı Buluyorum"],
      stories: [
          {
              title: "HİKAYE 1",
              text: "Okuldan eve geldiğinde Merve odasına giderek ders çalışır. Küçük kardeşi odaya girip ortalığı dağıtıp, Merve'nin oyuncaklarını ve eşyalarını karıştırıp izinsiz alır. Merve bu duruma çok sinirlenir ve birkaç kez uyardıktan sonra kardeşine vurur ve itekleyerek odadan çıkarır. Ayşe'nin ağlaması üzerine anne ve babası odaya gelir.",
              questions: [
                  "Anne ve babanın Merve'nin davranışı nedeniyle sevdiği bir şeyi yapmasını yasaklamasını",
                  "Anne ve babanın bu davranışı kuzenlerinin ya da komşu çocuklarının hiç yapmadığını, onların çok uyumlu olduğunu söylemesini",
                  "Anne ve babanın Merve'nin davranışı nedeniyle hakaret içerikli sözler söylemesini",
                  "Anne ve babanın Merve'nin davranışı nedeniyle ona lakap takmasını",
                  "Anne ve babanın Merve'nin davranışı nedeniyle sorularına cevap vermeyip duymazdan gelmesini",
                  "Anne ve babanın Merve'nin davranışı nedeniyle yüksek sesle bağırmasını",
                  "Anne ve babanın Merve'nin davranışı nedeniyle onu dövmesini"
              ]
          },
          {
              title: "HİKAYE 2",
              text: "Öğretmen dersteyken içeri giren görevli, acil bir durum olduğunu, okul müdürünün kendisiyle görüşmek istediğini belirtir. Öğretmen öğrencileri sessiz olmaları için tembihler ve beş dakika içerisinde döneceğini söyler. Öğretmen gerçekten de beş dakika sonra döner ama sınıfın yarısı bahçede, bir öğrenci arkadaşları tarafından alay edildiği için ağlamakta, diğerleri de ayakta ve çok aşırı gürültü yapmaktadır.",
              questions: [
                  "Öğretmenin bu davranış nedeniyle öğrencileri teneffüse çıkarmamasını",
                  "Öğretmenin böyle yaptıkları için sınıfa kırgın olduğunu belirtip bir süre küsmesini",
                  "Öğretmenin bunu yapan öğrencilere çok istedikleri tiyatro etkinliğinden çıkarmasını",
                  "Öğretmenin bunu yapan öğrencilere hakaret içeren sözcükler söylemesini",
                  "Öğretmenin olaylara karışan öğrencilere bağırmasını",
                  "Öğretmenin olaylara karışan öğrencileri itip kakmasını",
                  "Öğretmenin olaylara karışan öğrencilere tahta kalemi ya da başka bir şey fırlatmasını",
                  "Öğretmenin öğretmenler odasında olaya karışan öğrencilerin isimlerini verip fikir almasını",
                  "Öğretmenin kızgın olduğu için bir süre olaya karışan öğrencilerin sorularını duymazdan gelmesini",
                  "Öğretmenin olaylara karışan öğrencilere vurmasını"
              ]
          },
          {
              title: "HİKAYE 3",
              text: "Turgut, arkadaşları tarafından sevilen yardımsever, sevimli ve çalışkan bir çocuktur. Sınıf arkadaşları olan Taci, Turgut'un yakın arkadaşları ile samimi olmuş ama Turgut ile iyi anlaşamamıştır. Bir gün arkadaşları Turgut'a gelip Taci'nin kendisi hakkında dedikodu yaptığını söylemiştir. Bunun üzerine Turgut, Taci ile konuşmaya gittiğinde Taci Turgut'a küfür etmiştir.",
              questions: [
                  "Taci hakkında aslı olmayan hikayeler uydurmasını",
                  "Taci'ye kötü isimler takmasını",
                  "Taci'ye gidip bağırmasını",
                  "Taci'yi tehdit etmesini",
                  "Taci'ye aşağılayıcı şeyler söylemesini",
                  "Taci'ye küfür etmesini",
                  "Taci'yi bir fırsatını bulup itip kakmasını",
                  "Taci'nin saçını/kulağını çekmesini",
                  "Taci'yi yakalayıp dövmesini"
              ]
          }
      ]
    },
    { 
      id: 'riba_ilkokul', 
      title: 'RİBA (İlkokul-Öğrenci Formu)', 
      desc: 'Bu anketin amacı okulumuzda hangi rehberlik hizmetlerine ihtiyaç duyduğunuzu belirlemektir. Her soruda A ve B olmak üzere iki ifade verilmektedir. Sorulara yanıt verirken iki rehberlik hizmetinden hangisine daha çok ihtiyaç duyduğunuzu düşününüz. Soruda verilen iki rehberlik hizmetini karşılaştırınız ve her soruda iki hizmetten sadece bir tanesini seçiniz.', 
      type: 'riba', 
      questions: [
        { a: "Çevremdeki insanların mesleklerini öğrenmek (ör., Hastanede doktor ve hemşireler çalışır.)", b: "Okul kurallarını öğrenmek" },
        { a: "Gelecekte başarılı olmak için kendime uygun hedefler belirlemek (ör., Başarılı bir sporcu olmak isteyen bir öğrenci her gün antrenman yapar.)", b: "Severek yapabileceğim şeyleri öğrenmek (ör., Bir öğrenci sesi güzel olsun ya da olmasın şarkı söylemeyi sevebilir. Bu öğrencinin müziğe ilgisi vardır denir.)" },
        { a: "Bilgisayar, cep telefonu, tablet veya televizyonu kullanırken yaşıma uygun içerik seçmek ve kullanım süresini belirlemek", b: "Başkaları hatırlatmadan sorumluluklarımı yerine getirmek (ör., ödevlerimi tamamlamak; odamı, eşyalarımı düzenlemek, temiz tutmak vb.)" },
        { a: "Okulda, evde ve arkadaşlık ilişkilerimde doğru kararlar almak", b: "Bedenimi korumayı öğrenmek (ör., Başkalarının bedenime izinsiz dokunmasına izin vermemek)" },
        { a: "Sorunlarımı nasıl çözebileceğimi öğrenmek", b: "Rehber öğretmen/psikolojik danışmandan hangi konularda yardım alabileceğimi öğrenmek" },
        { a: "Yeni arkadaşlar edinmek ve arkadaşlarımla iyi geçinmeyi öğrenmek", b: "Oyun oynarken, ödev yaparken arkadaşlarımla yardımlaşmayı öğrenmek" },
        { a: "Tehlikeli olabilecek durumlarda dikkatli davranmayı öğrenmek (ör., Bu tehlikeli durumlar merdivenden dikkatsizce inip çıkmak, koridorda koşmak olabilir)", b: "Ders çalıştığım sırada silgiyle oynama, resim çizme gibi dikkatimi dağıtan davranışlardan uzak durmayı öğrenmek" },
        { a: "Ders çalışma ortamımı (odamı, masamı) nasıl düzenleyeceğimi bilmek", b: "Hangi ortaokullara gidebileceğimi öğrenmek" },
        { a: "Okula her gün mutlu bir şekilde gelme isteğimi artırmak", b: "Yaşadığım duyguları tanımak (ör., sevdiğim oyuncağı kaybettiğimde üzülmek, lunaparka gidince mutlu olmak)" },
        { a: "Duygularımı ve isteklerimi saygılı bir şekilde karşımdakine iletmek", b: "Zorbalıkla karşılaştığımda (ör., kötü söz söyleme, vurma) ne yapmam gerektiğini öğrenmek" },
        { a: "Bir çocuk olarak hak ve sorumluluklarımı öğrenmek", b: "Kolay öğrendiğim, başkalarından daha iyi yapabildiğim şeyleri öğrenmek (Bir öğrenci zor matematik sorularını hızlı ve doğru çözüyorsa matematiğe yeteneği var demektir. Çok hızlı koşuyorsa, spora yeteneği vardır.)" },
        { a: "Okuldaki kurslar, kulüpler (ör., spor, satranç, tiyatro) ve yarışmalar gibi etkinlikler hakkında bilgilenmek", b: "Nasıl ders çalışmam gerektiğini öğrenmek" },
        { a: "Başkalarının ne hissettiklerini ve ne düşündüklerini anlamak", b: "Derslerde zorlandığımda bile başarılı olacağıma inanmak" },
        { a: "“HAYIR!” diyebilmeyi öğrenmek (ör., bir şey yapmak istemediğimde ya da tehlikeli durumlardan kaçınmam gerektiğinde)", b: "Bir mesleğe sahip olmanın önemini anlamak (ör., Bir mesleğim olursa para kazanırım.)" },
        { a: "Ders çalışmak ve oyun oynamak için zamanı planlamayı öğrenmek", b: "Zorlandığım konularda doğru kişilerden yardım istemek (ör., zorbalığa uğradığımda bir yetişkinden yardım istemek; dersi anlamadığımda öğretmenden yardım istemek)" }
      ]
    },
    { 
      id: 'riba_ortaokul', 
      title: 'RİBA (Ortaokul-Öğrenci Formu)', 
      desc: 'Bu anketin amacı okulumuzda hangi rehberlik hizmetlerine ihtiyaç duyduğunuzu belirlemektir. Her soruda A ve B olmak üzere iki ifade verilmektedir. Sorulara yanıt verirken iki rehberlik hizmetinden hangisine daha çok ihtiyaç duyduğunuzu düşününüz. Soruda verilen iki rehberlik hizmetini karşılaştırınız ve her soruda iki hizmetten sadece bir tanesini seçiniz.', 
      type: 'riba', 
      questions: [
        { a: "Sorunları tanımlayıp çeşitli çözümler içinden en mantıklı olanı uygulamak", b: "Kendime uygun ders çalışma becerilerini geliştirmek (ör., plan yapmak, görselleştirmek, not çıkartmak, çalışma ortamımı düzenlemek)" },
        { a: "Hayatımla ilgili konularda karar verme becerilerimi geliştirmek (ör., kıyafet seçme, arkadaş seçme, okul seçme)", b: "Okula devam etme isteğimi artırmak" },
        { a: "Arkadaşlık kurma becerilerimi geliştirmek (ör., insanlarla tanışmak, arkadaş edinmek ve arkadaşlıklarımı sürdürmek)", b: "Liselere giriş sınavları hakkında bilgilenmek" },
        { a: "Okuldaki kulüpler (spor, satranç, tiyatro vb.) ve yarışmalar gibi etkinlikler hakkında bilgilenmek", b: "İlişkilerimi bozmadan haklarımı savunmayı öğrenmek" },
        { a: "Zorlandığım konularda doğru kişilerden yardım isteme becerilerimi geliştirmek (ör., zorbalığa uğradığımda rehber öğretmen/psikolojik danışmana ulaşmak; yapamadığım soruları arkadaşlara ya da öğretmene sormak)", b: "Başkaları hatırlatmadan sorumluluklarımı yerine getirmek (ör., ödevlerimi tamamlama; odamı, eşyalarımı düzenlemek, temiz tutmak)" },
        { a: "Duygularım (üzüntü, öfke, kaygı vb.) ortaya çıktığında, bunları kontrol etmeyi öğrenmek", b: "Bilgisayar, cep telefonu, tablet veya televizyonu kullanırken uygun içerik seçmek ve kullanım süresini belirlemek" },
        { a: "Zamanımı planlamayı öğrenmek (ör., ders çalışmak, arkadaşlarla buluşmak, oyun oynamak)", b: "Ergenlikteki değişikliklerle ilgili bilgilenmek (ör., bedendeki değişimler, sivilcelerin çıkması, anne ve babayla çatışmalar)" },
        { a: "Hak ve sorumluluklarımı öğrenmek", b: "Yeteneklerimi (neleri iyi yapabildiğimi) tanımak" },
        { a: "Ortaokuldan sonra gidebileceğim eğitim kurumlarını tanımak", b: "Yaşamdaki zorluklar karşısında duygusal açıdan dayanıklı olmak (ör., okul değiştirme, ebeveynlerin boşanması, yakınların ölümü)" },
        { a: "Madde kullanımı, oyun ve sosyal medya gibi bağımlılık türleri ve korunma yöntemleri hakkında bilgilenmek", b: "Duygu ve düşüncelerimi saygılı ve açık bir şekilde ifade etmek" },
        { a: "Kişisel özelliklerim ile belli meslekler arasında ilişkiler kurmak (Ör., Çocukları seven bir öğrencinin büyüyünce öğretmen olmayı istemesi)", b: "İnsanlarla anlaşmazlıklarımı, her iki tarafın da isteklerini karşılayacak şekilde çözmeyi öğrenmek" },
        { a: "Farklı özelliklere sahip bireylere saygı göstermeyi öğrenmek (ör., cinsiyet, özel gereksinimli öğrenci)", b: "Öfkemi kontrol etmek" },
        { a: "Bir şey yapmak istemediğimde “HAYIR” diyebilmek", b: "Okul ve sınıf kurallarını benimsemek" },
        { a: "İletişim becerilerimi geliştirmek (ör., karşımızdakinin beden ve yüz hareketlerinden duygularını tahmin etmek, söz kesmeden dinlemek)", b: "Rehber öğretmenden/psikolojik danışmandan hangi konularda yardım alabileceğimi öğrenmek" },
        { a: "Kendime güvenmeyi öğrenmek", b: "İlgilerimi (ör., kodlama, spor, resim ve müzik) keşfetmek" },
        { a: "Sınav kaygısı ile başa çıkmayı öğrenmek", b: "Bedenimi korumayı öğrenmek (ör., başkalarının bedenime izinsiz dokunmasına izin vermemek)" },
        { a: "Riskli davranışlardan kaçınmayı öğrenmek (ör., tehlikeli arkadaş gruplarına katılmaktan, okuldan kaçmaktan ve kavgaya karışmaktan kaçınmak)", b: "Sağlıklı yaşam becerilerini kazanmak (ör., spor yapmak, sağlıklı beslenmek)" },
        { a: "Zorbalığa uğradığımda ne yapmam gerektiğini öğrenmek (ör., alay etme, vurma, fotoğraflarımı sosyal medyada izinsiz paylaşma)", b: "Duygularımı (mutluluk, öfke, kaygı, üzüntü, korku, şaşkınlık gibi) tanımak" }
      ]
    },
    { 
      id: 'riba_lise', 
      title: 'RİBA (Lise-Öğrenci Formu)', 
      desc: 'Bu anketin amacı okulumuzda hangi rehberlik hizmetlerine ihtiyaç duyduğunuzu belirlemektir. Her soruda A ve B olmak üzere iki ifade verilmektedir. Sorulara yanıt verirken iki rehberlik hizmetinden hangisine daha çok ihtiyaç duyduğunuzu düşününüz. Soruda verilen iki rehberlik hizmetini karşılaştırınız ve her soruda iki hizmetten sadece bir tanesini seçiniz.', 
      type: 'riba', 
      questions: [
        { a: "İlişkilerimi bozmadan haklarımı savunmayı öğrenmek", b: "Verimli ders çalışma becerilerimi geliştirmek" },
        { a: "Stresle baş etmeyi öğrenmek", b: "Hayatımla ilgili konularda karar verme becerilerimi geliştirmek (ör., arkadaş seçme, okul seçme, kariyer planlama)" },
        { a: "Yaşamdaki zorluklar karşısında duygusal açıdan dayanıklı olmak (ör., okul değiştirme, ebeveynlerin boşanması, yakınların ölümü)", b: "Bir şeyi yapmak istemediğimde, “HAYIR” diyebilme becerisini kazanmak" },
        { a: "Yeteneklerimi (neleri iyi yapabildiğimi) tanımak", b: "Okul kuralları (sınıf geçme, ödül, disiplin gibi konular) hakkında bilgilenmek" },
        { a: "Ergenlik döneminin duygusal değişimleriyle ilgili bilgi edinmek", b: "İletişim becerilerimi güçlendirmek (ör., beden dilini anlamak, empati kurmak)" },
        { a: "Harekete geçmeden önce anlık isteğimi değil, davranışımın sonuçlarını göz önünde bulundurmak (ör., ders çalışırken telefonunu başka odaya koymak, tartışmalar şiddetlendiğinde ortamdan uzaklaşmak)", b: "Ergenlik dönemi gelişim özellikleri konusunda bilgilenmek (ör., bedensel ve ruhsal değişiklikler)" },
        { a: "İstismar (fiziksel, duygusal vb.) ve ihmal türlerinden korunmayı öğrenmek", b: "Üst öğrenim olanakları hakkında bilgilenmek" },
        { a: "Üniversite sınavları hakkında bilgilenmek", b: "Teknoloji bağımlılığından korunma becerilerimi geliştirmek" },
        { a: "Karşı cinsle sağlıklı iletişim kurabilme becerisi kazanmak", b: "Farklı kariyer seçeneklerinde nelerin gerekli olduğunu öğrenmek ve buna göre hedeflerimi gözden geçirmek (ör., deneme sınav sonuçlarıyla istediğim bölümlerin başarı sıralarını karşılaştırmak)" },
        { a: "Mesleklerle ilgili çeşitli kaynaklardan bilgi edinmek (ör., iş yerlerini gezme, meslek insanın okula davet edilmesi, internet kaynakları)", b: "İlgi, yetenek ve değerlerime uygun kariyer seçeneklerini analiz etmek" },
        { a: "Zorlandığım konularda doğru kişilerden yardım isteme becerilerimi geliştirmek (ör., zorbalığa uğradığımda rehber öğretmen/psikolojik danışmana ulaşmak; yapamadığım soruları arkadaşlara ya da öğretmene sormak)", b: "Öfkemi kontrol etme becerilerimi güçlendirmek" },
        { a: "Rehber öğretmenden/psikolojik danışmandan hangi konularda yardım alabileceğimi öğrenmek", b: "Bağımlılık yapan maddelerin etkileri hakkında bilgilenmek" },
        { a: "İnsanlarla anlaşmazlıklarımı, ilişkilerimi bozmayacak ve haklarımı savunacak şekilde çözmek", b: "Okul dışı etkinlikler (eğitsel, kültürel, sosyal ve sportif faaliyetler) hakkında bilgilenmek" },
        { a: "Sağlıklı yaşam becerilerini kazanmak (ör., spor yapmak, sağlıklı beslenmek, kişisel hijyene dikkat etmek)", b: "Meslek seçiminde nelere önem verildiğini öğrenmek (ör., işin kazancı, saygınlığı, çalışma ortamı)" },
        { a: "İlgilerimi (kodlama, spor, resim ve müzik) keşfetmek", b: "Dijital okur-yazarlık becerilerini geliştirmek (ör., sahte videoları ayırt etmek, kötü amaçlı yazılımları indirmemek ve kişisel verileri paylaşmamak)" },
        { a: "Özgüvenimi geliştirmek", b: "Zamanı planlama becerilerimi geliştirmek" },
        { a: "Okul kulüpleri (spor, satranç, tiyatro vb.) ve yarışmalar gibi etkinlikler hakkında bilgilenmek", b: "Sınav kaygısı ile başa çıkmayı öğrenmek" },
        { a: "Zorbalığa uğradığımda ne yapmam gerektiğini öğrenmek (ör., alay etme, vurma, fotoğraflarımı sosyal medyada izinsiz paylaşma)", b: "Aile üyeleriyle iletişimimi güçlendirmek" },
        { a: "Duygularımı düzenlemeyi öğrenmek (ör., öfkelenince, üzülünce, kaygılanınca sakinleşmek için yürüyüşe çıkmak, biriyle dertleşmek, olaylara farklı açıdan bakmak)", b: "Farklı özelliklere sahip bireylere saygı göstermeyi öğrenmek (ör., karşı cins, özel gereksinimli birey ve göçmenler)" },
        { a: "Okula devam etme isteğimi artırmak", b: "Okulda seçebileceğim alan/dal hakkında bilgilenmek" }
      ]
    },
    {
      id: 'verimli_ders_calisma',
      title: 'Verimli Ders Çalışma Kontrol Listesi',
      desc: 'Okul başarısında etkili olan verimli ders çalışma yöntem ve teknikleri hakkındaki bilgilerinizi değerlendirmek amacıyla hazırlanmıştır. Her madde için Evet, Kısmen veya Hayır seçeneklerinden size en uygun olanı işaretleyiniz.',
      type: 'checklist_matrix',
      questions: [
        { header: 'A. AMAÇLARIN VE ÖNCELİKLERİN BELİRLENMESİ' },
        "Zamanı verimli kullanmak için kısa, orta ve uzun dönemli hedefler belirlerim.",
        "Belirlediğim hedeflerimi her zaman göreceğim bir yere koyarım.",
        "Hedeflerim arasında öncelik sırası belirlerim.",
        "Hedeflerimi gerçekleştirmek üzere her gün belirli bir zaman ayırır ve ayırdığım bu zamana uyarım.",
        { header: 'B. ZAMANI DÜZENLEMEK VE PROGRAM YAPMAK' },
        "Başarılı olmak için enerjimi okul ile ilgili hedeflerim doğrultusunda kullanırım.",
        "Çalışma planı yaparken nasıl, ne zaman ve nerede çalışacağıma karar veririm.",
        "Çalışma planımda her ders ya da konuya ayrılacak süreyi kendi öğrenme hızıma göre planlarım.",
        "Aynı anda birden fazla iş yapmak yerine bunlardan birini seçer ve ona odaklanırım.",
        "Ders çalışırken belirli aralıklarla mola veririm.",
        "Çalışma planımda derslerimi aksatmayacak şekilde sosyal ve kültürel faaliyetlere yer veririm.",
        "Çalışma planımda okula, dinlenmeye, ev ile ilgili sorumluluklarıma ve uykuya ayırdığım süreyi belirtirim.",
        "Çalışma saatlerimi kendimi dinlenmiş hissettiğim zamanlara göre planlarım.",
        "Verimsiz geçirdiğim zamanların farkına varırım ve gerekli önlemleri alırım.",
        "Teknolojik aletlere (TV, bilgisayar, telefon vb.) ayırdığım zamanı kısıtlarım.",
        "Uzun konuları küçük parçalara bölerek çalışırım.",
        "Hatırlamayı kolaylaştırmak için şekil (şema, grafik, tablo) çizerek çalışırım.",
        "Çalışmayı bitirmeden önce notlarımı hızlıca gözden geçiririm.",
        "Öğrendiklerimi, uyumadan önce ve sabah kalkınca hızlı bir şekilde gözden geçiririm.",
        "Öğrendiklerimi ihtiyaç duyduğumda günlük hayatta kullanırım.",
        { header: 'C. ÇALIŞMA ORTAMINA İLİŞKİN DÜZENLEMELER' },
        "Çalışma masamın yüksekliği boyuma uygundur.",
        "Çalışma masamı yalnızca ders çalışmak için kullanırım.",
        "Çalışmaya başlamadan önce gerekli araç gereçleri hazır bulundururum.",
        "Sürekli aynı yerde ders çalışırım.",
        "Her zaman masa veya sehpada ve oturarak çalışırım.",
        "Çalışma ortamımın sessiz sakin olmasına dikkat ederim.",
        "Çalışma ortamımın düzenli ve sade olmasına dikkat ederim.",
        "Çalışma masamda, öğreneceğim konu dışındaki materyalleri kaldırırım.",
        "Ders çalışırken aynı zamanda başka bir işle (TV izlemek, müzik dinlemek, telefonla konuşmak vb.) uğraşmamaya dikkat ederim.",
        "Çalışma ortamıma dersle ilgili hatırlatıcı notlar asarım.",
        "Çalışma ortamımda dikkatimi dağıtan afiş, poster vb. bulundurmam.",
        "Çalışma ortamım ne çok sıcak ne çok soğuktur.",
        "Çalışma ortamımı düzenli olarak havalandırırım.",
        "Hayal kurduğumu fark ettiğimde ders çalışmaya ara veririm.",
        "Hayal kurmayı dinlenme aralarında kendime ödül olarak veririm.",
        "Ders çalışmaya başlamadan önce çalışacağım konunun ana ve alt başlıklarını, ilk ve son paragraflarını gözden geçiririm.",
        { header: 'D. ETKİN OKUMA' },
        "Çalışacağım konu ile ilgili olarak ayrıntılı sorular hazırlarım.",
        "Hazırladığım soruların cevabını bulmak için tekrar tekrar okurum.",
        "Hazırladığım soruları kendi kendime anlatarak cevaplarım.",
        "Öğrendiklerimi unutmamak için günlük, haftalık, aylık tekrar yaparım.",
        { header: 'E. ETKİN DİNLEME' },
        "Dinlerken hangi konunun önemli olduğunu ayırt ederim.",
        "Her konuya ait ana fikirleri anlamaya çalışırım.",
        "Öğretmenin özellikle üzerinde durduğu noktalara dikkat ederim.",
        "Anlamadığım konularda soru sorarak, eksik bulduğum yerleri tamamlayarak derse katılırım.",
        "Dinlediğim konuyu ayrıntılı öğrenmek için başka kaynaklardan (kitap, internet vb.) yararlanırım.",
        "Derste not tutarım.",
        { header: 'F. DERSE HAZIRLIKLI GELMEK' },
        "O gün işlenecek konuları okuyarak derse gelirim.",
        "İşlenecek konular ile ilgili anlamadığım noktaları derste öğretmene sorarım."
      ]
    },
    {
      id: 'yasam_pencerem',
      title: 'YAŞAM PENCEREM',
      desc: 'Sevgili Öğrenciler; Sizleri daha iyi tanımak, anlamak ve sizlere ihtiyaç duyduğunuz konularda destek olabilmek için aşağıda bazı ifadeler sunulmuştur. Bu durumlardan size uygun olanların başındaki kutucuğa (X) işareti koyunuz. Teşekkür ederiz.',
      type: 'yasam_pencerem',
      questions: [
        { text: "Sürekli devam eden bir hastalığım var. Varsa yazınız...", hasText: true },
        { text: "Ailem benim bir üst öğrenime devam etmemi istemiyor." },
        { text: "Deprem/yangın/sel/savaş/trafik kazası vb. durumlarından en az birini yaşadım. Evet ise hangisi?", hasText: true },
        { text: "Değerlerimi/inançlarımı yaşayabileceğim ortam sağlanmıyor." },
        { text: "Daha önce yaşamadığım bazı korkularım var." },
        { text: "Öfkemi kontrol edemiyorum." },
        { text: "Arkadaşlarımdan bazıları bağımlılık yapıcı madde kullanıyor." },
        { text: "Teknoloji ile (cep telefonu, tablet, internet vs.) çok vakit geçiriyorum." },
        { text: "Çoğu zaman kimseyle konuşmak\\görüşmek istemiyorum." },
        { text: "Ailemin benden beklentisi çok yüksek." },
        { text: "Aile ortamımızda sık sık tartışma olur." },
        { text: "Arkadaşlık kurmakta zorlanıyorum." },
        { text: "Fiziksel güce ihtiyacım olduğunda beni destekleyecek bir grubun üyesiyim." },
        { text: "Temel ihtiyaçlarımızı karşılayacak maddi olanaklardan yoksunum." },
        { text: "Çevremdeki insanlar tarafından istemediğim söz ve hareketlere maruz kalıyorum." },
        { text: "Hoşlanmadığım davranışlara zorlanıyorum." },
        { text: "Ailemin geçimini sağlamak için bir işte çalışıyorum." },
        { text: "Hayatı yaşamaya değer bulmuyorum." },
        { text: "Ailemi bana ve ihtiyaçlarıma (maddi, manevi) karşı ilgisiz buluyorum." },
        { text: "Fiziksel görünüşümden rahatsızım." },
        { text: "Ailemiz içerisinde belli kurallar yoktur." },
        { text: "Ailemde zararlı alışkanlıkları olan birey/bireyler var." },
        { text: "Kendime hiç güvenim yok." },
        { text: "Ailemden ayrı yaşıyorum. Çünkü...", hasText: true },
        { text: "Yaşamım üzerinde hiç kontrolüm yok." },
        { text: "Kendimi belirli bir alanda çok yetenekli buluyorum." },
        { text: "Okul dışında kaliteli vakit geçireceğim aktiviteler yapacak fırsatım yok." },
        { text: "İstesem de derslerimde başarılı olamıyorum." },
        { text: "Annem/babam okuma yazma bilmiyor." },
        { text: "Başkaları ile kıyaslanıyorum." },
        { text: "Dersler ilgi çekici hale getirilmiyor." },
        { text: "Okulu bitirdikten sonra ne yapmak istediğimi bilmiyorum." },
        { text: "Okulu sevmiyorum." },
        { text: "Fazla heyecanlanıyorum." },
        { text: "Okulda problemlerimizle fazla ilgilenilmiyor." },
        { text: "Okulda kendimi güvende hissetmiyorum." },
        { text: "Kendimi herhangi bir alanda yetenekli bulmuyorum." },
        { text: "Ailem teknoloji ile (cep telefonu, tablet, internet vs.) çok vakit geçiriyor." },
        { text: "Farklı tercihlerimden dolayı çevrem tarafından dışlanıyorum." },
        { text: "Okuldaki disiplin anlayışından rahatsızım." },
        { text: "Sevdiğim bir yakınımı kaybettiğim için çok üzgünüm. Lütfen yazınız...", hasText: true },
        { text: "Okulda yeteri kadar sosyal etkinlik düzenlenmiyor." },
        { text: "Okulda alınan kararlarda öğrencilerin görüşü alınmıyor." },
        { text: "Öğrenci sorunları öğrencilerle çözülmek yerine önce ailelere aktarılıyor." },
        { text: "Öğrenciler arasında ayrım yapılıyor." },
        { text: "Okula uyum sağlayamadım." },
        { text: "Ailemden biri/birileri şehit/gazi oldu." },
        { text: "Okul yeterince temiz değil." }
      ],
      footer: "Eklemek istedikleriniz..."
    }
];
