export const hollandConfig = {
    id: "holland",
    title: "HOLLAND MESLEKİ TERCİH ENVANTERİ",
    desc: "AÇIKLAMA: Her maddeyi okuyun ve size uygun yanıtı işaretleyin.",
    type: "matrix",
    columns: ["Hoşlanırım", "Farketmez", "Hoşlanmam"],
    questions: [
        "Kuşların nasıl göç ettiğini öğrenmek",
        "İnsanlara yeni bir hobi öğretmek",
        "Hava durumu tahmini için kişisel gözlemleri kullanmak",
        "Bitki hastalıklarını incelemek",
        "Bankaya yatırılan paranın faizini hesaplamak",
        "Resimler tasarlamak ve çizmek",
        "Bir iş yaptırmak için parayla adam tutmak",
        "Bir bilim müzesini incelemek",
        "Gözlük için mercekleri parlatmak",
        "Modern yazarların yazı stillerini araştırmak",
        "Mikroskop gibi laboratuar aletlerini kullanmak",
        "Bir dükkanda envanter tutmak",
        "Bir kuş yemliği tasarlamak",
        "Bir oyun için takım oluşturma",
        "Yeni bir satış kampanyası düzenlemek",
        "Bir toplantıyı yönetmek",
        "Vitaminlerin hayvanlar üzerindeki etkisini araştırmak",
        "Küçük bir işletmeyi idare etmek",
        "Bir makinenin nasıl kullanılacağı konusunda talimatlar yazmak",
        "Diğer insanlar için iş planlamak",
        "Küçük grup tartışmalarına katılmak",
        "Yeni bir cerrahi işlem hakkında yazılar okumak",
        "Mali bir hesaptaki hataları bulmak",
        "Bir rapor taslağındaki hataları bulmak incelemek",
        "Planlar ve grafikler yapmak",
        "Fırtınadan sonra zarar görmüş bir ağacı onarmak",
        "Kusurları bulmak için mamulleri incelemek",
        "Telefonla iş idare etmek",
        "Acil durumlarda insanlara yardım etmek",
        "Bir kuruluşun parayla ilgili bütün işlerini idare etmek",
        "Müzik eseri bestelemek veya düzenlemek",
        "Filmler için konu müziği bestelemek",
        "Yeni kurallar veya politikalar geliştirmek",
        "Biyoloji çalışmak",
        "Bir politik kurum için kampanyaya katılmak",
        "Maddeleri ayırmak, biriktirmek ve saklamak",
        "Bir toplum geliştirme projesinde çalışmak",
        "Bir daktilonun nasıl tamir edileceğini öğrenmek",
        "Dünyanın merkezi, güneş ve yıldızlar hakkında kitaplar okumak",
        "Tam doğru zaman tutmak için bir saati ayarlamak",
        "Beynin nasıl çalıştığını öğrenmek",
        "Yaratıcı fotoğraflar çekmek",
        "Masraflara ait hesap kayıtları tutmak",
        "Bir bandoda çalmak",
        "Bir orkestrada caz müziği çalmak",
        "Bir grup veya klüp için bütçe hazırlamak",
        "Depremin nedenlerini araştırmak",
        "Ünlü bir bilim adamının dersine katılmak",
        "Bir proje üzerinde başkaları ile beraber çalışmak",
        "Bir sinema filmi senaryosu yazmak",
        "Şirket hakkındaki şikayetleri konusunda işçilerle röportaj yapmak",
        "Mobilya yapmak",
        "Değerli taşları kesmeyi ve parlatmayı öğrenmek",
        "Yaralı bir insana ilkyardım yapmak",
        "Yerel bir radyo istasyonunda çalınması için müzik parçaları seçmek",
        "İl genel meclisinde çalışmak",
        "Mali raporları hazırlamak ve yorumlamak",
        "Tehlikedeki bir insana yardım etmeye çalışmak",
        "Elektronik alet çalıştırmak",
        "Çocuklara nasıl oyun oynanacağını veya spor yapılacağını göstermek",
        "Bir ustayı televizyon tamir ederken seyretmek",
        "Bir magazin hikayesini anlatan çizimler yapmak",
        "Ziyaretçilere yol göstermek",
        "Diğer insanların bir problemin çözülebileceğine nasıl inandıklarını öğrenmek",
        "Bir sergiye gezi düzenlemek",
        "Uyuşturucu kullanan insanlara danışmanlık yapmak",
        "İş gazeteleri veya dergileri okumak",
        "Yıldızların oluşumunu öğrenmek",
        "Taksit ödemelerini tahsil etmek",
        "Bir slayt veya film projektörünü çalıştırmak",
        "Kelebekleri gözlemlemek ve sınıflandırmak",
        "Metal bir heykel tasarlamak",
        "İnsanlara kanuni doğruları açıklamak",
        "Kısa hikayeler yazmak",
        "İnsanların mali kararlar vermelerine yardımcı olmak",
        "Gelir vergisi kazancını düzenlemek",
        "Sertifika, plaket veya taktir belgesi kazanmak",
        "Tiyatro oyunu, müzikaller gibi sanatsal etkinliklerin eleştirilerini yazmak",
        "Aylık bütçe planı yapmak",
        "Bir havuz veya gölde yabani hayatı araştırmak",
        "Bir tiyatro oyununda rol almak",
        "Bir resim çerçevesi yapmak",
        "İş gezilerine çıkmak",
        "Orman yangınları için gözetleme yapmak",
        "Yeni alışveriş merkezinin tanıtımını yapmak",
        "Bir muhasebecilik sistemi kurmak",
        "Arkadaşlar arasındaki bir tartışmayı yatıştırmak",
        "Birine önemli bir karar vermesinde yardım etmek",
        "Taşıma için nakil maliyetlerini hesaplamak",
        "Fıkralar ve hikayeler anlatarak insanları eğlendirmek"
    ]
};
