export const INITIAL_SURVEY_FORMS_CONFIG = [
  {
    id: "ogrenci_memnuniyet",
    title: "ÖĞRENCİ MEMNUNİYETİ ANKETİ",
    desc: "Sizlere daha kaliteli hizmet verebilmek için okuldaki uygulamalarla ilgili görüşlerinize ihtiyaç duyulmaktadır.",
    type: "matrix",
    columns: ["TAM (5)", "ÇOK (4)", "ORTA (3)", "AZ (2)", "HİÇ (1)"],
    questions: [
      { text: "İhtiyaç duyduğumda okul yöneticileriyle rahatlıkla görüşebilirim.", category: "Ulaşılabilirlik ve İletişim" },
      { text: "İhtiyaç duyduğumda öğretmenlerle rahatlıkla görüşebilirim.", category: "Ulaşılabilirlik ve İletişim" },
      { text: "İhtiyaç duyduğumda okul çalışanlarıyla rahatlıkla görüşebilirim.", category: "Ulaşılabilirlik ve İletişim" },
      { text: "Sınıf başkanımız, dilek, öneri ve şikayetlerimizi ilgili kişilere ulaştırır.", category: "Dilek, Öneri ve Şikayetler" },
      { text: "Arkadaşlarımla ilgili sorunlarım, öğretmenlerim tarafından dikkate alınır.", category: "Dilek, Öneri ve Şikayetler" },
      { text: "Okulumuzla ilgili isteklerimiz dikkate alınır.", category: "Dilek, Öneri ve Şikayetler" },
      { text: "Okulumuz yöneticilerine güvenirim.", category: "Güvenilirlik" },
      { text: "Okulumuz öğretmenlerine güvenirim.", category: "Güvenilirlik" },
      { text: "Okulumuzun diğer çalışanlarına güvenirim.", category: "Güvenilirlik" },
      { text: "Okul yolu (varsa okul servisleri) güvenlidir.", category: "Güvenlik" },
      { text: "Okulda yabancı kişilere karşı güvenlik önlemleri alınmaktadır.", category: "Güvenlik" },
      { text: "Okulda yangın ve doğal afetlere (Deprem, sel, vb.) karşı gerekli güvenlik önlemler alınır.", category: "Güvenlik" },
      { text: "Okulumuzda bizimle ilgili kararlarda görüşlerimiz dikkate alınır.", category: "Kararlara Katılım" },
      { text: "Okuldan istediğim belgeleri (öğrenci belgesi, kimlik) zamanında alabilirim.", category: "Öğrenci işleri" },
      { text: "Okulumuzda sağlık sorunu yaşadığımızda gerekli hassasiyet gösterilir.", category: "Öğrenci işleri" },
      { text: "Dersler seviyemize uygun olarak işlenir.", category: "Eğitim-Öğretim" },
      { text: "Okulda edindiğim bilgilerin şimdi veya ileriki hayatımda işime yarayacağını düşünüyorum.", category: "Eğitim-Öğretim" },
      { text: "Derslerin işlenişinde bilgisayar, tepegöz, harita gibi araç-gereçlerden yararlanılmaktadır.", category: "Eğitim-Öğretim" },
      { text: "Aradığım kaynakları (Ansiklopedi vs.) okulda bulabiliyorum.", category: "Eğitim-Öğretim" },
      { text: "Okulumuzdan mezun olduktan sonra gidebileceğim bir üst eğitim kurumu hakkında yönlendirme yapılmaktadır.", category: "Eğitim-Öğretim" },
      { text: "Teneffüs süreleri yeterlidir.", category: "Ders Arası" },
      { text: "Teneffüslerde bir sorun olduğunda nöbetçi öğretmenler hemen müdahale ederler.", category: "Ders Arası" },
      { text: "Okul her zaman temiz ve bakımlıdır.", category: "Okulun Fiziki Ortamı" },
      { text: "Okulumuz kantininde satılan yiyecek ve içeceklerin fiyatları uygundur", category: "Okulun Kantin ve Yemekhanesi" },
      { text: "Okul kantininde ihtiyaç duyduğum, beğendiğim ürünleri bulabiliyorum", category: "Okulun Kantin ve Yemekhanesi" },
      { text: "Okulun yemekhanesi temiz ve sağlıklıdır", category: "Okulun Kantin ve Yemekhanesi" },
      { text: "Okulda yeterli miktarda sosyal ve kültürel faaliyet düzenlenmektedir.", category: "Sosyal, Kültürel ve Spor Etkinlikleri" },
      { text: "Düzenlenen sosyal ve kültürel faaliyetlere severek katılıyorum.", category: "Sosyal, Kültürel ve Spor Etkinlikleri" },
      { text: "Okulum sahip olduğum yetenekleri geliştirme imkanı sağlar.", category: "Sosyal, Kültürel ve Spor Etkinlikleri" },
      { text: "Katıldığım kulüp faaliyetlerinden bir çok şey öğrendim.", category: "Eğitici Kol Çalışmaları" },
      { text: "Okulumuzda belirli gün ve haftalarla ilgili kutlamalar yapılmaktadır.", category: "Belirli Gün ve Haftalar" },
      { text: "Okulumuzda yapılan belirli gün ve hafta kutlamalarını beğeniyorum", category: "Belirli Gün ve Haftalar" },
      { text: "Okulda ders içi ve ders dışı başarılar ile örnek davranışlarımız ödüllendirilir", category: "Değerlendirme,Ödül, Teşekkür ve Takdir Belgeleri" },
      { text: "Öğretmenler sınav sonuçlarının değerlendirmesinde tarafsız davranırlar.", category: "Değerlendirme,Ödül, Teşekkür ve Takdir Belgeleri" },
      { text: "Ödüllendirme ve cezalandırmalarda tarafsız ve adil davranılır.", category: "Değerlendirme,Ödül, Teşekkür ve Takdir Belgeleri" },
      { text: "Okulda milli ve manevi değerlerimiz benimsetilmektedir.", category: "Olumlu Davranış Kazanma ve Eğitim" },
      { text: "Okulda temel ahlaki değerler kazandırılmaktadır.", category: "Olumlu Davranış Kazanma ve Eğitim" },
      { text: "Tercih şansım olsa yine bu okulu seçerdim.", category: "Olumlu Davranış Kazanma ve Eğitim" }
    ],
    openQuestions: [
      "Okulumuzda en çok neleri seviyorsunuz?",
      "Okulumuzda neleri değiştirmek isterdiniz?"
    ]
  },
  {
    id: "veli_memnuniyet",
    title: "VELİ MEMNUNİYETİ ANKETİ",
    desc: "Değerli velimiz, sizlere daha kaliteli hizmet verebilmek için okuldaki uygulamalarla ilgili görüşlerinize ihtiyaç duyulmaktadır.",
    type: "matrix",
    demographics: [
      { name: "Cinsiyetiniz", options: ["Kadın", "Erkek"] },
      { name: "Yaşınız", options: ["18-25 yaş", "26-33 yaş", "34-41 yaş", "42-49 yaş", "50 yaş ve üzeri"] },
      { name: "Eğitim durumunuz?", options: ["İlköğretim", "Ortaöğretim (lise)", "Yüksek Okul", "Fakülte (Lisans)", "Yüksek lisans ve üstü"] },
      { name: "Kaç yıldır bu okuldan hizmet alıyorsunuz?", options: ["0-1 yıl", "1-2 yıl", "2-3 yıl", "3 ve üstü"] }
    ],
    columns: ["TAM (5)", "ÇOK (4)", "ORTA (3)", "AZ (2)", "HİÇ (1)"],
    questions: [
      { text: "İhtiyaç duyduğumda okul personeliyle rahatlıkla görüşebiliyorum.", category: "Ulaşılabilirlik ve İletişim" },
      { text: "Bizi ilgilendiren okul duyurularını zamanında öğreniyorum.", category: "Ulaşılabilirlik ve İletişim" },
      { text: "Okuldaki veli toplantıları ihtiyaçlarıma cevap verecek şekilde düzenlenmektedir.", category: "Ulaşılabilirlik ve İletişim" },
      { text: "Okuldan, ihtiyacım olan konularda rehberlik hizmeti almaktayım.", category: "Ulaşılabilirlik ve İletişim" },
      { text: "Okul ile ilgili istek ve şikâyetlerimi okula iletebiliyorum.", category: "Dilek, Öneri ve Şikayetler" },
      { text: "Okula ilettiğim istek ve şikâyetlerim dikkate alınıyor.", category: "Dilek, Öneri ve Şikayetler" },
      { text: "Okul yöneticilerine güvenirim.", category: "Güvenilirlik" },
      { text: "Okulun öğretmenlerine güvenirim.", category: "Güvenilirlik" },
      { text: "Okulda yabancı kişilere karşı güvenlik önlemleri alınmaktadır.", category: "Güvenlik" },
      { text: "Okulda yangın ve doğal afetlere (Deprem, sel, vb.) karşı gerekli güvenlik önlemleri alınır.", category: "Güvenlik" },
      { text: "Okul yolu (varsa okul servisleri) güvenlidir.", category: "Güvenlik" },
      { text: "Okul-Aile Birliği Yönetim Kurulu tüm velileri temsil edebilmektedir.", category: "Kararlara Katılım" },
      { text: "Okulda bizleri ilgilendiren kararlarda görüşlerimiz dikkate alınır.", category: "Kararlara Katılım" },
      { text: "Okulla etkileşim ve ilgi düzeyiniz için bir değerlendirmede bulununuz.", category: "Kararlara Katılım" },
      { text: "Öğrenci devamsızlık bilgilerine rahatlıkla ulaşabiliyorum.", category: "Öğrenci işleri" },
      { text: "Öğrencimin notlarını rahatlıkla takip edebiliyorum.", category: "Öğrenci işleri" },
      { text: "Öğrenci işleri ile ilgili belgeler zamanında düzenlenir.", category: "Öğrenci işleri" },
      { text: "Çocuğumuz anlamadığı bir şeyi öğretmenine rahatlıkla sorabilmektedir", category: "Eğitim-Öğretim" },
      { text: "Çocuğumuz okulda öğretim anlamında yeterli bilgiyi alabilmektedir.", category: "Eğitim-Öğretim" },
      { text: "Okulda eğitim-öğretimin sağlıklı bir şekilde yürütülmesi için yeterli sayıda görevli vardır.", category: "Eğitim-Öğretim" },
      { text: "Okul her zaman temiz ve bakımlıdır.", category: "Okulun Fiziki Ortamı" },
      { text: "Okul, öğrencilerin sağlığı, gelişimi açısından uygun fiziki ortama sahiptir", category: "Okulun Fiziki Ortamı" },
      { text: "Okulun kantininde satılan malzemeler temiz ve sağlıklıdır.", category: "Okulun Kantin, Yemekhane ve Yatakhaneleri" },
      { text: "Okul kantininde satılan malzemeler hesaplıdır.", category: "Okulun Kantin, Yemekhane ve Yatakhaneleri" },
      { text: "Okuldaki sosyal etkinlikler öğrencimin yeteneklerini geliştirecek şekilde düzenlenmektedir.", category: "Sosyal, Kültürel ve Spor Etkinlikleri" },
      { text: "Öğrencim okulda sosyalleşti.", category: "Sosyal, Kültürel ve Spor Etkinlikleri" },
      { text: "Okulda öğrencimin farkında olmadığım yetenekleri ortaya çıktı.", category: "Sosyal, Kültürel ve Spor Etkinlikleri" },
      { text: "Öğrenci başarıları değerlendirilirken tarafsız davranıldığını düşünüyorum", category: "Değerlendirme, Ödül, Teşekkür ve Takdir Belgeleri" },
      { text: "Öğrencim okuldaki başarıları ödüllendirilir.", category: "Değerlendirme, Ödül, Teşekkür ve Takdir Belgeleri" },
      { text: "Öğrencim okulda milli ve manevi değerleri öğrenebilmektedir.", category: "Olumlu Davranış Kazanma ve Eğitim" },
      { text: "Öğrencim okulda temel ahlak kurallarını öğrenebilmektedir.", category: "Olumlu Davranış Kazanma ve Eğitim" },
      { text: "Okulda öğrencim olumlu bir kişilik kazanabilmektedir.", category: "Olumlu Davranış Kazanma ve Eğitim" },
      { text: "Okul çalışanları ve öğrenciler davranışlarıyla çevreye iyi örnek olur.", category: "Topluma Etki ve Katkı Durumunun Algılanması" },
      { text: "Çevreden okulla ilgili olumlu eleştiriler duyarım.", category: "Topluma Etki ve Katkı Durumunun Algılanması" },
      { text: "Bu okulu başkalarına da tavsiye ederim.", category: "Topluma Etki ve Katkı Durumunun Algılanması" }
    ],
    openQuestions: [
      "Okulda en etkili olduğunu düşündüğünüz uygulama nedir?",
      "Diğer görüşlerinizi de belirtebilirsiniz."
    ]
  },
  {
    id: "ogretmen_memnuniyet",
    title: "ÖĞRETMEN MEMNUNİYETİ ANKETİ",
    desc: "Bu anket ile okulumuz hakkındaki görüşleriniz alınacaktır.",
    type: "matrix",
    columns: ["Kesinlikle Katılıyorum (5)", "Katılıyorum (4)", "Kararsızım (3)", "Katılmıyorum (2)", "Hiç Katılmıyorum (1)"],
    questions: [
      { text: "Yöneticiler, çalışanların hizmet içi eğitim ihtiyaçlarını karşılamak için kişi ve kuruluşlarla işbirliği yapar.", category: "Kariyer Belirleme" },
      { text: "Çalıştığım okul bana kendimi geliştirme imkânı tanımaktadır.", category: "Kariyer Belirleme" },
      { text: "Yöneticiler, çalışanların mesleklerinde gelişmeleri için gerekli desteği verir.", category: "Kariyer Belirleme" },
      { text: "Kurumdaki tüm duyurular çalışanlara zamanında iletilir.", category: "İletişim" },
      { text: "Okulumuzda yapılan faaliyetlerde herkes birbirine yardımcı olur.", category: "İletişim" },
      { text: "Okul yöneticileri ile sağlıklı iletişim kurabiliyorum.", category: "İletişim" },
      { text: "Okulda, öğretmenler ile sağlıklı iletişim kurabiliyorum.", category: "İletişim" },
      { text: "Okulumuza yeni gelen her çalışana okul hakkında tanıtıcı bilgi verilmektedir.", category: "İletişim" },
      { text: "Okulda, diğer çalışanlar ile sağlıklı iletişim kurabiliyorum.", category: "İletişim" },
      { text: "Okulumuzun sorunlarının çözümünde insiyatif kullanma olanağına sahibim.", category: "Yetkilendirme" },
      { text: "Okulda işimle ilgili insiyatif kullanma olanağına sahibim.", category: "Yetkilendirme" },
      { text: "Okulda bilgi ve becerilerimi sergileme olanağına sahibim.", category: "Yetkilendirme" },
      { text: "Okulda görev alanıma giren iş ve işlemlerin yürütülmesine liderlik yapma fırsatı tanınmaktadır.", category: "Yetkilendirme" },
      { text: "Okulda işimle ilgili yeterli düzeyde yetki sahibiyim.", category: "Yetkilendirme" },
      { text: "Okulumuzda, çalışanlar arasında her türlü fırsat eşitliği sağlanmaktadır.", category: "Fırsat Eşitliği" },
      { text: "Okulumuzda çalışanlara yaptıkları işlerde destek olunarak işlerini başarma fırsatı sağlanmaktadır.", category: "Fırsat Eşitliği" },
      { text: "Okulumuzla çalışanlarla ilgili kararlar, çalışanların katılımıyla demokratik bir şekilde alınır.", category: "Kararlara Katılım" },
      { text: "Okulda çalışanların dile getirdiği şikâyet ve öneriler dikkate alınmaktadır.", category: "Kararlara Katılım" },
      { text: "Okulumuzun kalite politikasını destekliyorum.", category: "Kararlara Katılım" },
      { text: "Yöneticilerimiz çalışanların görüşlerini dikkate almaktadır.", category: "Yönetimden Memnuniyet" },
      { text: "Yöneticilerimiz işinin gerektirdiği yeterliliğe sahiptir.", category: "Yönetimden Memnuniyet" },
      { text: "Yöneticilerimiz insan ilişkilerine önem vermektedir.", category: "Yönetimden Memnuniyet" },
      { text: "Yöneticilerimiz, yaratıcı ve yenilikçi düşüncelerin üretilmesini teşvik etmektedir.", category: "Yönetimden Memnuniyet" },
      { text: "Okulda üstlerim liderlik davranışları sergilemektedir.", category: "Yönetimden Memnuniyet" },
      { text: "Yöneticilerimiz, teknolojik gelişmeleri takip etmektedir.", category: "Yönetimden Memnuniyet" },
      { text: "Okulumuzun değerleri, misyonu, vizyonu, politika ve stratejisi tüm çalışanların katılımıyla belirlenmektedir.", category: "Okulun Vizyon, Misyon ve Değerlerine İlişkin" },
      { text: "Okulumuzun değerlerini, misyonu, vizyonu, politika ve stratejilerini biliyorum.", category: "Okulun Vizyon, Misyon ve Değerlerine İlişkin" },
      { text: "Okulumuzun değerlerini, misyonu, vizyonu, politika ve stratejilerini benimsiyorum.", category: "Okulun Vizyon, Misyon ve Değerlerine İlişkin" },
      { text: "Yöneticilerimiz, okulda birlikte çalışmayı destekler.", category: "Destek" },
      { text: "Yöneticiler, çalışanların değişim yaratacak fikirleri desteklenmektedir.", category: "Destek" },
      { text: "Yöneticiler, okulun vizyonunu, stratejilerini, iyileştirmeye açık alanlarını vs. çalışanlarla paylaşır.", category: "Destek" },
      { text: "Yöneticiler, iyileştirme takım çalışmalarının önerilerini dikkate alarak iyileştirmeler yapar.", category: "Destek" },
      { text: "Okulumuz çalışanlarına internet, bilgisayar, fotokopi vb. teknolojik imkânlar sunulmaktadır.", category: "Okulda Bulunan Araç, Gereç" },
      { text: "Okulda ihtiyaç duyduğum malzemeye zamanında ulaşabilirim.", category: "Okulda Bulunan Araç, Gereç" },
      { text: "Okulda çalışanlara, sınıflara/bürolara yapılan araç gereç dağıtımında eşitlik ilkesi uygulanır.", category: "Okulda Bulunan Araç, Gereç" },
      { text: "Kendimi okulun değerli bir üyesi olarak görürüm.", category: "Okul Ortamı" },
      { text: "Okulda kendimi güvende hissederim.", category: "Okul Ortamı" },
      { text: "Yaptığım işten zevk alıyorum ve işimi seviyorum.", category: "Okul Ortamı" },
      { text: "Okul yönetiminden memnunum.", category: "Okul Ortamı" },
      { text: "Yöneticilerin sergilediği tutum ve davranışlar, çalışanları motive edici yöndedir.", category: "Okul Ortamı" },
      { text: "Çalışanlara yönelik sosyal ve kültürel faaliyetler düzenlenir.", category: "Çalışanlara Sağlanması Gereken Hizmetler" },
      { text: "Okulda düzenlenen sosyal ve kültürel faaliyetlere severek katılmaktayım.", category: "Çalışanlara Sağlanması Gereken Hizmetler" },
      { text: "Okulumuz genel toplum üzerinde olumlu etkiye sahiptir.", category: "Genel Memnuniyet" },
      { text: "Çalışanlar kendilerini okulda güvende hissetmektedirler.", category: "Genel Memnuniyet" },
      { text: "Çalışanlar hastalandıklarında okul yönetimince gerekli kolaylık sağlanmaktadır.", category: "Genel Memnuniyet" },
      { text: "Okulun yönetim sisteminden memnuniyet duyulmaktadır.", category: "Genel Memnuniyet" },
      { text: "Çalışanlar okulun yönetim süreçlerine etkin biçimde katılmaktadırlar.", category: "Genel Memnuniyet" },
      { text: "Okulumuzda, çalışanların mezun oldukları alanlar dikkate alınmakta yapılacak işlerde bundan yararlanılmaktadır.", category: "Genel Memnuniyet" },
      { text: "Okulumuz çalışanlarına öğretmenler odası, sigara içme odası, temiz ve bakımlı tuvaletler, çay vb. imkânlar sunulmaktadır.", category: "Genel Memnuniyet" },
      { text: "Okulumuzun bir web sayfası bulunmakta ve bu sayfada çalışanlar tanıtılmaktadır.", category: "Genel Memnuniyet" }
    ],
    openQuestions: [
      "Genel Notlar ve Eklemek İstedikleriniz"
    ]
  }
];
